# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regexapp', '0002_auto_20170813_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card_manager',
            name='unique_id',
            field=models.CharField(default='YZXcnDRS1036jHAezTVhtfKg2gh09X6s', max_length=32, primary_key=True, serialize=False),
        ),
    ]
