# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regexapp', '0003_auto_20170813_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game_Num',
            fields=[
                ('unique_id', models.CharField(default='vHphmURX8VnLRQmzKz32bbm2nKQMFKsj', max_length=32, primary_key=True, serialize=False)),
                ('well_being', models.BigIntegerField()),
                ('money', models.BigIntegerField()),
                ('popularity', models.BigIntegerField()),
                ('veg', models.BigIntegerField()),
                ('pizza', models.BigIntegerField()),
                ('pizzar', models.BigIntegerField()),
                ('shoe', models.BigIntegerField()),
                ('partner', models.BigIntegerField()),
                ('veg_cost_money', models.BigIntegerField()),
                ('pizza_cost_money', models.BigIntegerField()),
                ('pizzar_cost_money', models.BigIntegerField()),
                ('shoes_cost_money', models.BigIntegerField()),
                ('partner_cost_money', models.BigIntegerField()),
                ('partner_cost_pop', models.BigIntegerField()),
                ('cs_demand', models.BigIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Card_Manager',
        ),
    ]
