# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regexapp', '0004_auto_20170813_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game_num',
            name='cs_demand',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='game_num',
            name='money',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='game_num',
            name='partner',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='game_num',
            name='partner_cost_money',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='game_num',
            name='partner_cost_pop',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='game_num',
            name='pizza',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='game_num',
            name='pizza_cost_money',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='game_num',
            name='pizzar',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='game_num',
            name='pizzar_cost_money',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='game_num',
            name='popularity',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='game_num',
            name='shoe',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='game_num',
            name='shoes_cost_money',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='game_num',
            name='unique_id',
            field=models.CharField(default='UZbbyHPGvXgUHtZR4EqmVjLhuj8uu5V0', max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='game_num',
            name='veg',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='game_num',
            name='veg_cost_money',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='game_num',
            name='well_being',
            field=models.BigIntegerField(null=True),
        ),
    ]
