# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regexapp', '0007_auto_20170813_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game_num',
            name='unique_id',
            field=models.CharField(default='Fw6qN8hU4RRN5lza9G4k069qA1wKJxt9', max_length=32, primary_key=True, serialize=False),
        ),
    ]
