# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regexapp', '0012_auto_20170813_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game_num',
            name='unique_id',
            field=models.CharField(default='7S0x3GyKSet6C6sqTjcTFUO1d5eyy3Qj', max_length=32, primary_key=True, serialize=False),
        ),
    ]
