# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regexapp', '0023_auto_20170813_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game_num',
            name='unique_id',
            field=models.CharField(default='wCFHtl2ux02iGuJV4yb7St7L2iYVQ4pm', max_length=32, primary_key=True, serialize=False),
        ),
    ]
