# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regexapp', '0024_auto_20170813_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game_num',
            name='unique_id',
            field=models.CharField(default='mRE2GAdHdASo2x3eRRXWBWA7jwvU8C6N', max_length=32, primary_key=True, serialize=False),
        ),
    ]
