# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regexapp', '0031_auto_20170814_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game_num',
            name='unique_id',
            field=models.CharField(default='WXwDBATdEAlyRXJEGbozBP7FH4UWQzc1', max_length=32, primary_key=True, serialize=False),
        ),
    ]
