# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regexapp', '0032_auto_20170814_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game_num',
            name='unique_id',
            field=models.CharField(default='oXQX1Is2Y6JCJJ6ibCfTM2T2oSW1VM2u', max_length=32, primary_key=True, serialize=False),
        ),
    ]
