# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regexapp', '0033_auto_20170814_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game_num',
            name='unique_id',
            field=models.CharField(default='25X1RTp55Mi3jy3GNupsKOfvznAgt6PY', max_length=32, primary_key=True, serialize=False),
        ),
    ]
