# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regexapp', '0038_auto_20170814_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game_num',
            name='unique_id',
            field=models.CharField(default='HS04rU1QDcQwEqBAmhBy5cdFwoRvGx2M', max_length=32, primary_key=True, serialize=False),
        ),
    ]
