# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regexapp', '0040_auto_20170814_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game_num',
            name='unique_id',
            field=models.CharField(default='cbqSG1ImaCNVG6G8d3qrdsP46ijGT9Go', max_length=32, primary_key=True, serialize=False),
        ),
    ]
